import:
  - ~/.config/alacritty/theme.yml

window:
  dimensions:
    columns: 0
    lines: 0

  decorations: none

  startup_mode: Windowed

  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

hints:
  mouse:
    enabled: true
    mods: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
working_directory: None
