#!/usr/bin/env bash
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR_PRIMARY=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITOR_PRIMARY="${MONITOR_PRIMARY:-${MONITORS[0]}}"

MULTI=false
if [[ "${#MONITORS[@]}" -gt "1" ]]; then
	MULTI=true
fi

bspc monitor "${MONITOR_PRIMARY}" -d 1 2 3 4

if [[ "${MULTI}" ]] && [[ "${MONITORS[@]}" =~ "${MONITOR_MULTI_COMMS}" ]]; then
	bspc monitor "${MONITOR_MULTI_COMMS}" -d comms
fi

if [[ "${MULTI}" ]] && [[ "${MONITORS[@]}" =~ "${MONITOR_MULTI_ETC}" ]]; then
	bspc monitor "${MONITOR_MULTI_ETC}" -d etc
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

## Comms Monitor
if [[ "${MULTI}" ]] && [[ "${MONITOR_MULTI_COMMS}" -z ]]; then
	bspc rule -a Slack desktop=comms
	bspc rule -a Signal desktop=comms
fi

## Wide Monitor
if [[ "${MULTI}" ]] && [[ "${MONITOR_MULTI_ETC}" -z ]]; then
	bspc rule -a 'Emacs:org*' desktop=etc
	bspc rule -a KeePassXC desktop=etc
	bspc rule -a firefox desktop=etc
fi

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
