#!/usr/bin/env bash
export PRIMARY_MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
PRIMARY_MONITOR=${PRIMARY_MONITOR:-${MONITORS[0]}}

# Only have switchable desktops for the primary monitor
for monitor in $MONITORS; do
  bspc monitor $monitor -d 0
done
bspc monitor $PRIMARY_MONITOR -d {1,2,3}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

bspc rule -a Spotify desktop=3
bspc rule -a KeePassXc state=floating
bspc rule -a 'Emacs:org*' state=floating

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
