#!/usr/bin/env bash
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
export PRIMARY_MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
PRIMARY_MONITOR=${PRIMARY_MONITOR:-${MONITORS[0]}}

STANDARD_MONITOR="DP-1-2"
WIDE_MONITOR="DP-1-3"

bspc monitor $PRIMARY_MONITOR -d 1 2 3 4

if [[ ${MONITORS[@]} =~ ${STANDARD_MONITOR} ]]; then
	bspc monitor $STANDARD_MONITOR -d std
fi

if [[ ${MONITORS[@]} =~ ${WIDE_MONITOR} ]]; then
	bspc monitor $WIDE_MONITOR -d wide
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

## Main Monitor
bspc rule -a Spotify desktop=3
bspc rule -a Discord desktop=4

## Standard Monitor
bspc rule -a Slack desktop=std
bspc rule -a Signal desktop=std

## Wide Monitor
bspc rule -a 'Emacs:org*' desktop=wide
bspc rule -a KeePassXC desktop=wide

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
