{ config, options, pkgs, lib, ... }:

with lib;
with lib.my;
let cfg = config.modules.shell.weechat;
    configDir = config.dotfiles.configDir;
in {
  options.modules.shell.weechat = with types; {
    enable = mkBoolOpt false;
  };

  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      (weechat.override {
        configure = { availablePlugins, ... }: {
          scripts = with pkgs.weechatScripts; [
            wee-slack
          ];
        };
      })
    ];

    # home.configFile = {
    #   "tmux" = { source = "${configDir}/tmux"; recursive = true; };
    #   "tmux/extraInit" = {
    #     text = ''
    #       #!/usr/bin/env bash
    #       # This file is auto-generated by nixos, don't edit by hand!
    #       ${concatMapStrings (path: "tmux source-file '${path}'\n") cfg.rcFiles}
    #       tmux run-shell '${pkgs.tmuxPlugins.copycat}/share/tmux-plugins/copycat/copycat.tmux'
    #       tmux run-shell '${pkgs.tmuxPlugins.prefix-highlight}/share/tmux-plugins/prefix-highlight/prefix_highlight.tmux'
    #       tmux run-shell '${pkgs.tmuxPlugins.yank}/share/tmux-plugins/yank/yank.tmux'
    #       tmux run-shell '${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/resurrect.tmux'
    #     '';
    #     executable = true;
    #   };
    # };
  };
}
